name: 'My library'
services:
  db_my_library:
    image: 'postgres'
    container_name: 'db_my_library'
    ports:
      - 5432:5432
    env_file: 'private/db.env'
    volumes:
      - db_my_library:/var/lib/postgresql/data
    networks:
      - network_my_library

  app_node:
    image: 'node:22-alpine'
    container_name: app_node
    volumes:
      - .:/var/www/html
    networks:
      - network_my_library
    working_dir: /var/www/html
    command: ['npm', 'run', 'watch']
    tty: true
    stdin_open: true

  app_my_library:
    image: 'my_library'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    container_name: app_my_library
    volumes:
      - app_my_library_var:/var/www/html/var/
      - .:/var/www/html
    networks:
      - network_my_library
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db_my_library
      - app_node

volumes:
  db_my_library:
  app_my_library_var:

networks:
  network_my_library: